;;;; overlays/crisp-compiler-overlay.lisp
;;;;
;;;; Runtime patches for compiler improvements
;;;; Applied via late binding - last definition wins

(in-package :crisp.compiler)


;;; =========================================================
;;; 050-differentiate-and-metadata: backward kernel metacrisp
;;; =========================================================

;; src/metadata.lisp
(defun %bwd-resolve-type (type-spec &optional new-access)
  "Resolves TYPE-SPEC alias to its inline form. If NEW-ACCESS (:read-only or :write-only)
   is provided and the resolved type is a cell, replaces the :access keyword value.
   Used to build semantically correct declared-types for backward kernel metadata (Option B)."
  (cl:let* ((resolved (resolve-type-alias type-spec))
             (is-cell (and (consp resolved)
                           (symbolp (first resolved))
                           (string-equal (symbol-name (first resolved)) "CELL"))))
    (if (and is-cell new-access)
        (cl:let* ((pos (position :access resolved))
                  (new-spec (copy-list resolved)))
          (if pos
              (progn (setf (nth (1+ pos) new-spec) new-access)
                     new-spec)
              (append resolved (list :access new-access))))
        resolved)))

;; src/metadata.lisp
(defun %bwd-fixup-declared-types (bwd-k-name)
  "Reads BWD-K-NAME's entry in *kernel-declared-signatures*, produces semantically
   correct inline types (Option B), and updates the entry in place.
   Rules:
     - Params before &out: resolve alias, force cell :access to :read-only
     - Params after  &out: resolve alias, force cell :access to :write-only
   This corrects the raw types stored by %generate-backward-kernel-ast, which
   copies them mechanically from the forward kernel's type list."
  (cl:let ((raw-types (gethash bwd-k-name *kernel-declared-signatures*)))
    (when raw-types
      (cl:let* ((out-mode nil)
                (semantic-types
                  (mapcar (cl:lambda (pair)
                            (cl:let* ((p  (car pair))
                                      (ts (cdr pair)))
                              (cond
                                ((and (symbolp p) (string-equal (symbol-name p) "&OUT"))
                                 (setf out-mode t)
                                 pair)
                                (t
                                 (cl:let ((access (if out-mode :write-only :read-only)))
                                   (cons p (%bwd-resolve-type ts access)))))))
                          raw-types)))
        (setf (gethash bwd-k-name *kernel-declared-signatures*) semantic-types)
        semantic-types))))

;; src/metadata.lisp
(defun generate-metadata-for-file (input-path output-path &key (output-targets nil) (source-file nil) (forms nil))
  "Generates .metacrisp sidecar files for each kernel in INPUT-PATH.
   In differentiate mode (*differentiate-p*), generates metadata for the backward
   (_GRAD) kernel rather than the forward kernel, while preserving the file-name
   convention established by main.lisp (output-path already carries the _grad prefix)."
  (let ((kernel-names (if forms
                          (extract-defined-kernels forms)
                          (alexandria:hash-table-keys *function-table*)))
        (generated-files nil))

    (let ((src-path (or source-file
                        (namestring input-path))))

      (when (null kernel-names)
        (multiple-value-bind (aliases structs)
            (collect-kernel-dependencies nil)
          (declare (ignore aliases structs))
          (with-open-file (stream output-path :direction :output :if-exists :supersede)
            (format stream ";; generated by crisp-compile~%~%")))
        (push output-path generated-files))

      (dolist (k kernel-names)
        ;; In differentiate mode, look up the backward kernel (k_GRAD) for all content.
        ;; The file name still uses k, because output-path already has the _grad prefix
        ;; added by main.lisp, giving e.g. "01-multiply_grad_cell_mult.metacrisp".
        (let* ((effective-k (if *differentiate-p*
                                (intern (format nil "~a_GRAD" (symbol-name k))
                                        (symbol-package k))
                                k))
               (final-path (make-pathname
                             :name (format nil "~a_~a"
                                           (pathname-name output-path)
                                           (string-downcase (symbol-name k)))
                             :type "metacrisp"
                             :defaults output-path)))

          ;; Fix up backward kernel's declared types before serialization:
          ;; resolve aliases to inline types and correct cell access modes.
          (when *differentiate-p*
            (%bwd-fixup-declared-types effective-k))

          (multiple-value-bind (aliases structs)
              (collect-kernel-dependencies (list effective-k))
            (with-open-file (stream final-path :direction :output :if-exists :supersede)
              (format stream ";; generated by crisp-compile~%~%")
              (serialize-aliases stream aliases)
              (serialize-structs stream structs)
              (serialize-kernels stream (list effective-k)
                                 :source src-path
                                 :output-targets output-targets)))

          (push final-path generated-files)))

      (nreverse generated-files))))
