;;;; overlays/crisp-compiler-overlay.lisp
;;;;
;;;; Runtime patches for compiler improvements
;;;; Applied via late binding - last definition wins

(in-package :crisp.compiler)


;;; =========================================================
;;; 050-differentiate-and-metadata: backward kernel metacrisp
;;; =========================================================

;; src/metadata.lisp
(defun %bwd-resolve-type (type-spec &optional new-access)
  "Resolves TYPE-SPEC alias to its inline form. If NEW-ACCESS (:read-only or :write-only)
   is provided and the resolved type is a cell, replaces the :access keyword value.
   Used to build semantically correct declared-types for backward kernel metadata (Option B)."
  (cl:let* ((resolved (resolve-type-alias type-spec))
             (is-cell (and (consp resolved)
                           (symbolp (first resolved))
                           (string-equal (symbol-name (first resolved)) "CELL"))))
    (if (and is-cell new-access)
        (cl:let* ((pos (position :access resolved))
                  (new-spec (copy-list resolved)))
          (if pos
              (progn (setf (nth (1+ pos) new-spec) new-access)
                     new-spec)
              (append resolved (list :access new-access))))
        resolved)))

;; src/metadata.lisp
(defun %bwd-fixup-declared-types (bwd-k-name)
  "Reads BWD-K-NAME's entry in *kernel-declared-signatures*, produces semantically
   correct inline types (Option B), and updates the entry in place.
   Rules:
     - Params before &out: resolve alias, force cell :access to :read-only
     - Params after  &out: resolve alias, force cell :access to :write-only
   This corrects the raw types stored by %generate-backward-kernel-ast, which
   copies them mechanically from the forward kernel's type list."
  (cl:let ((raw-types (gethash bwd-k-name *kernel-declared-signatures*)))
    (when raw-types
      (cl:let* ((out-mode nil)
                (semantic-types
                  (mapcar (cl:lambda (pair)
                            (cl:let* ((p  (car pair))
                                      (ts (cdr pair)))
                              (cond
                                ((and (symbolp p) (string-equal (symbol-name p) "&OUT"))
                                 (setf out-mode t)
                                 pair)
                                (t
                                 (cl:let ((access (if out-mode :write-only :read-only)))
                                   (cons p (%bwd-resolve-type ts access)))))))
                          raw-types)))
        (setf (gethash bwd-k-name *kernel-declared-signatures*) semantic-types)
        semantic-types))))

;; src/metadata.lisp
(defun generate-metadata-for-file (input-path output-path &key (output-targets nil) (source-file nil) (forms nil))
  "Generates .metacrisp sidecar files for each kernel in INPUT-PATH.
   In differentiate mode (*differentiate-p*), generates metadata for the backward
   (_GRAD) kernel rather than the forward kernel, while preserving the file-name
   convention established by main.lisp (output-path already carries the _grad prefix)."
  (let ((kernel-names (if forms
                          (extract-defined-kernels forms)
                          (alexandria:hash-table-keys *function-table*)))
        (generated-files nil))

    (let ((src-path (or source-file
                        (namestring input-path))))

      (when (null kernel-names)
        (multiple-value-bind (aliases structs)
            (collect-kernel-dependencies nil)
          (declare (ignore aliases structs))
          (with-open-file (stream output-path :direction :output :if-exists :supersede)
            (format stream ";; generated by crisp-compile~%~%")))
        (push output-path generated-files))

      (dolist (k kernel-names)
        ;; In differentiate mode, look up the backward kernel (k_GRAD) for all content.
        ;; The file name still uses k, because output-path already has the _grad prefix
        ;; added by main.lisp, giving e.g. "01-multiply_grad_cell_mult.metacrisp".
        (let* ((effective-k (if *differentiate-p*
                                (intern (format nil "~a_GRAD" (symbol-name k))
                                        (symbol-package k))
                                k))
               (final-path (make-pathname
                             :name (format nil "~a_~a"
                                           (pathname-name output-path)
                                           (string-downcase (symbol-name k)))
                             :type "metacrisp"
                             :defaults output-path)))

          ;; Fix up backward kernel's declared types before serialization:
          ;; resolve aliases to inline types and correct cell access modes.
          (when *differentiate-p*
            (%bwd-fixup-declared-types effective-k))

          (multiple-value-bind (aliases structs)
              (collect-kernel-dependencies (list effective-k))
            (with-open-file (stream final-path :direction :output :if-exists :supersede)
              (format stream ";; generated by crisp-compile~%~%")
              (serialize-aliases stream aliases)
              (serialize-structs stream structs)
              (serialize-kernels stream (list effective-k)
                                 :source src-path
                                 :output-targets output-targets)))

          (push final-path generated-files)))

      (nreverse generated-files))))


;;; =========================================================
;;; 050-differentiate-and-metadata: validators
;;; =========================================================

;; src/metadata-val.lisp
(defun validate-multiply-grad-metadata (paths)
  "Validates the backward grad metacrisp for 01-multiply/cell_mult_grad kernel.
   (A B &out C) -> backward: (A B C C_grad &out A_grad B_grad)
   Checks: kernel name, physical sig (18 params = 6 cells x 3),
   declared sig: a/b/c/c_grad (:in :read-only), a_grad/b_grad (:out :write-only),
   and source path present."
  (let* ((paths (if (listp paths) paths (list paths)))
         (meta-path (find "multiply_grad_cell_mult.metacrisp" paths
                         :test #'search :key #'namestring)))
    (unless meta-path
      (log:error "validate-multiply-grad-metadata: no *multiply_grad_cell_mult.metacrisp* in ~a" paths)
      (return-from validate-multiply-grad-metadata nil))
    (let* ((content (uiop:read-file-forms meta-path))
           (kernels (find :kernels content :key #'car))
           (k-def   (find-if (lambda (k) (string-equal (getf k :name) "cell_mult_grad"))
                             (cdr kernels))))
      (unless k-def
        (log:error "validate-multiply-grad-metadata: kernel 'cell_mult_grad' not found in ~a" meta-path)
        (return-from validate-multiply-grad-metadata nil))
      ;; Physical signature: 18 params (6 cells x 3)
      (let ((phys-sig (getf k-def :physical-signature)))
        (unless (= (length phys-sig) 18)
          (log:error "validate-multiply-grad-metadata: expected 18 physical-sig entries, got ~a"
                     (length phys-sig))
          (return-from validate-multiply-grad-metadata nil)))
      ;; Declared signature: 6 params with correct names, directions, access modes
      (let ((decl-sig (getf k-def :declared-signature)))
        (unless (= (length decl-sig) 6)
          (log:error "validate-multiply-grad-metadata: expected 6 declared-sig params, got ~a"
                     (length decl-sig))
          (return-from validate-multiply-grad-metadata nil))
        (flet ((check-cell (param expected-name expected-dir expected-access)
                 (let ((name   (getf param :name))
                       (dir    (getf param :direction))
                       (access (getf param :access)))
                   (unless (and (string-equal name expected-name)
                                (eq dir expected-dir)
                                (eq access expected-access))
                     (log:error "validate-multiply-grad-metadata: param ~s: expected dir=~s access=~s, got name=~s dir=~s access=~s"
                                expected-name expected-dir expected-access name dir access)
                     (return-from validate-multiply-grad-metadata nil)))))
          (check-cell (nth 0 decl-sig) "a"      :in  :read-only)
          (check-cell (nth 1 decl-sig) "b"      :in  :read-only)
          (check-cell (nth 2 decl-sig) "c"      :in  :read-only)
          (check-cell (nth 3 decl-sig) "c_grad" :in  :read-only)
          (check-cell (nth 4 decl-sig) "a_grad" :out :write-only)
          (check-cell (nth 5 decl-sig) "b_grad" :out :write-only)))
      ;; Source path present
      (unless (getf k-def :source)
        (log:error "validate-multiply-grad-metadata: no :source in kernel def")
        (return-from validate-multiply-grad-metadata nil))
      t)))

;; src/metadata-val.lisp
(defun validate-record-grad-metadata (paths)
  "Validates the backward grad metacrisp for 03-record-at-boundary.
   The record v-point (x float, y float) is exploded to scalar fields at the boundary.
   Checks: kernel name, physical sig (14 params), declared sig (6 params):
     vp_x/vp_y (float scalars, :in), c/c_grad (cells, :in :read-only),
     vp_x_grad/vp_y_grad (cells, :out :write-only), and source path present."
  (let* ((paths (if (listp paths) paths (list paths)))
         (meta-path (find "_grad_non_overloadable_accessor_k.metacrisp" paths
                         :test #'search :key #'namestring)))
    (unless meta-path
      (log:error "validate-record-grad-metadata: no *_grad_non_overloadable_accessor_k.metacrisp* in ~a" paths)
      (return-from validate-record-grad-metadata nil))
    (let* ((content (uiop:read-file-forms meta-path))
           (kernels (find :kernels content :key #'car))
           (k-def   (find-if (lambda (k)
                               (string-equal (getf k :name) "non_overloadable_accessor_k_grad"))
                             (cdr kernels))))
      (unless k-def
        (log:error "validate-record-grad-metadata: kernel 'non_overloadable_accessor_k_grad' not found in ~a"
                   meta-path)
        (return-from validate-record-grad-metadata nil))
      ;; Physical signature: 14 params
      ;;   vp_x (float=1) + vp_y (float=1) + c (cell=3) + c_grad (cell=3)
      ;;   + vp_x_grad (cell=3) + vp_y_grad (cell=3) = 14
      (let ((phys-sig (getf k-def :physical-signature)))
        (unless (= (length phys-sig) 14)
          (log:error "validate-record-grad-metadata: expected 14 physical-sig entries, got ~a"
                     (length phys-sig))
          (return-from validate-record-grad-metadata nil)))
      ;; Declared signature: 6 params
      (let ((decl-sig (getf k-def :declared-signature)))
        (unless (= (length decl-sig) 6)
          (log:error "validate-record-grad-metadata: expected 6 declared-sig params, got ~a"
                     (length decl-sig))
          (return-from validate-record-grad-metadata nil))
        (flet ((check-scalar-in (param expected-name)
                 (let ((name (getf param :name))
                       (dir  (getf param :direction)))
                   (unless (and (string-equal name expected-name) (eq dir :in))
                     (log:error "validate-record-grad-metadata: param ~s: expected float :in, got name=~s dir=~s"
                                expected-name name dir)
                     (return-from validate-record-grad-metadata nil))))
               (check-cell (param expected-name expected-dir expected-access)
                 (let ((name   (getf param :name))
                       (dir    (getf param :direction))
                       (access (getf param :access)))
                   (unless (and (string-equal name expected-name)
                                (eq dir expected-dir)
                                (eq access expected-access))
                     (log:error "validate-record-grad-metadata: param ~s: expected dir=~s access=~s, got name=~s dir=~s access=~s"
                                expected-name expected-dir expected-access name dir access)
                     (return-from validate-record-grad-metadata nil)))))
          (check-scalar-in (nth 0 decl-sig) "vp_x")
          (check-scalar-in (nth 1 decl-sig) "vp_y")
          (check-cell      (nth 2 decl-sig) "c"        :in  :read-only)
          (check-cell      (nth 3 decl-sig) "c_grad"   :in  :read-only)
          (check-cell      (nth 4 decl-sig) "vp_x_grad" :out :write-only)
          (check-cell      (nth 5 decl-sig) "vp_y_grad" :out :write-only)))
      ;; Source path present
      (unless (getf k-def :source)
        (log:error "validate-record-grad-metadata: no :source in kernel def")
        (return-from validate-record-grad-metadata nil))
      t)))
