(in-package :crisp.hoist.l0)

(defun main ()
  "Entry point for crisp-hoist-l0.exe"
  (handler-case
      (let ((args (uiop:command-line-arguments)))
        (format t "Crisp Hoist L0 - Level Zero C++ Launcher Generator~%")
        (format t "Version: 0.1.0~%~%")

        (unless args
          (format t "Usage: crisp-hoist-l0 <path-to-metacrisp-file>~%")
          (uiop:quit 1))

        (let ((metacrisp-path (first args)))
          (unless (probe-file metacrisp-path)
            (format t "Error: File not found: ~a~%" metacrisp-path)
            (uiop:quit 1))

          (format t "Processing: ~a~%" metacrisp-path)
          (generate-l0-launcher metacrisp-path)
          (format t "Done!~%")
          (uiop:quit 0)))
    (error (e)
      (format t "Error: ~a~%" e)
      (uiop:quit 1))))

(defun generate-l0-launcher (metacrisp-path)
  "Generate Level Zero C launcher code from metacrisp file."
  (let* ((data (parse-metacrisp-file metacrisp-path))
         (kernels (metacrisp-kernels data))
         (base-name (pathname-name metacrisp-path)))

    (format t "Processing ~a~%" metacrisp-path)
    (format t "  Kernels: ~a~%" (length kernels))

    ;; Generate one .cpp file per kernel
    (dolist (kernel kernels)
      (let* ((kernel-name (getf kernel :name))
             (output-targets (getf kernel :output-targets))
             (spv-path (when output-targets
                             (second (first output-targets)))) ;; Get first .spv path
             (output-name (format nil "~a_~a_hoist_L0.cpp" base-name kernel-name))
             (output-path (make-pathname :name (pathname-name output-name)
                                         :type "cpp"
                                         :defaults metacrisp-path)))

        (format t "  Generating: ~a~%" output-name)

        ;; Generate Level Zero C launcher
        (with-open-file (stream output-path :direction :output :if-exists :supersede)
          ;; Preamble comment
          (format stream "/*~%")
          (format stream " * Generated by crisp-hoist-l0~%")
          (format stream " * Source: ~a~%" (namestring metacrisp-path))
          (format stream " * Kernel: ~a~%" kernel-name)
          (format stream " *~%")
          (format stream " * Compilation:~%")
          (format stream " *   clang -o launcher.exe ~a -I<path-to-level-zero>/include~%" output-name)
          (format stream " *~%")
          (format stream " * Level Zero SDK: https://github.com/oneapi-src/level-zero/releases~%")
          (format stream " */~%~%")

          ;; Includes
          (format stream "#include <ze_api.h>~%")
          (format stream "#include <stdio.h>~%")
          (format stream "#include <stdlib.h>~%")
          (format stream "#include <string.h>~%~%")

          ;; Helper function for reading SPIR-V file
          (format stream "// Helper: Read SPIR-V binary from file~%")
          (format stream "unsigned char* read_spirv_file(const char* filename, size_t* size) {~%")
          (format stream "    FILE* f = fopen(filename, \"rb\");~%")
          (format stream "    if (!f) return NULL;~%")
          (format stream "    fseek(f, 0, SEEK_END);~%")
          (format stream "    *size = ftell(f);~%")
          (format stream "    fseek(f, 0, SEEK_SET);~%")
          (format stream "    unsigned char* data = (unsigned char*)malloc(*size);~%")
          (format stream "    fread(data, 1, *size, f);~%")
          (format stream "    fclose(f);~%")
          (format stream "    return data;~%")
          (format stream "}~%~%")

          ;; Main function
          (format stream "int main() {~%")
          (format stream "    ze_result_t result;~%")
          (format stream "    printf(\"Level Zero Launcher for kernel: ~a\\n\");~%~%" kernel-name)

          ;; Initialize Level Zero
          (format stream "    // Initialize Level Zero~%")
          (format stream "    result = zeInit(ZE_INIT_FLAG_GPU_ONLY);~%")
          (format stream "    if (result != ZE_RESULT_SUCCESS) {~%")
          (format stream "        printf(\"ERROR: zeInit failed: %%d\\n\", result);~%")
          (format stream "        return 1;~%")
          (format stream "    }~%~%")

          ;; Device discovery
          (format stream "    // Discover drivers~%")
          (format stream "    uint32_t driverCount = 0;~%")
          (format stream "    result = zeDriverGet(&driverCount, NULL);~%")
          (format stream "    if (result != ZE_RESULT_SUCCESS || driverCount == 0) {~%")
          (format stream "        printf(\"ERROR: No Level Zero drivers found\\n\");~%")
          (format stream "        return 1;~%")
          (format stream "    }~%~%")

          (format stream "    ze_driver_handle_t driver;~%")
          (format stream "    driverCount = 1;~%")
          (format stream "    zeDriverGet(&driverCount, &driver);~%~%")

          (format stream "    // Discover devices~%")
          (format stream "    uint32_t deviceCount = 0;~%")
          (format stream "    result = zeDeviceGet(driver, &deviceCount, NULL);~%")
          (format stream "    if (result != ZE_RESULT_SUCCESS || deviceCount == 0) {~%")
          (format stream "        printf(\"ERROR: No Level Zero devices found\\n\");~%")
          (format stream "        return 1;~%")
          (format stream "    }~%~%")

          (format stream "    ze_device_handle_t device;~%")
          (format stream "    deviceCount = 1;~%")
          (format stream "    zeDeviceGet(driver, &deviceCount, &device);~%")
          (format stream "    printf(\"Found Level Zero device\\n\");~%~%")

          ;; Create context
          (format stream "    // Create context~%")
          (format stream "    ze_context_desc_t contextDesc = {~%")
          (format stream "        .stype = ZE_STRUCTURE_TYPE_CONTEXT_DESC~%")
          (format stream "    };~%")
          (format stream "    ze_context_handle_t context;~%")
          (format stream "    result = zeContextCreate(driver, &contextDesc, &context);~%")
          (format stream "    if (result != ZE_RESULT_SUCCESS) {~%")
          (format stream "        printf(\"ERROR: zeContextCreate failed: %%d\\n\", result);~%")
          (format stream "        return 1;~%")
          (format stream "    }~%~%")

          ;; Module loading (if SPV path available)
          (when spv-path
                (format stream "    // Load SPIR-V module~%")
                (format stream "    const char* spv_path = \"~a\";~%" (namestring spv-path))
                (format stream "    size_t spirv_size;~%")
                (format stream "    unsigned char* spirv_data = read_spirv_file(spv_path, &spirv_size);~%")
                (format stream "    if (!spirv_data) {~%")
                (format stream "        printf(\"ERROR: Failed to read SPIR-V file: %%s\\n\", spv_path);~%")
                (format stream "        return 1;~%")
                (format stream "    }~%~%")

                (format stream "    ze_module_desc_t moduleDesc = {~%")
                (format stream "        .stype = ZE_STRUCTURE_TYPE_MODULE_DESC,~%")
                (format stream "        .format = ZE_MODULE_FORMAT_IL_SPIRV,~%")
                (format stream "        .inputSize = spirv_size,~%")
                (format stream "        .pInputModule = spirv_data~%")
                (format stream "    };~%~%")

                (format stream "    ze_module_handle_t module;~%")
                (format stream "    result = zeModuleCreate(context, device, &moduleDesc, &module, NULL);~%") ;(format stream "    result = zeModuleCreate(device, &moduleDesc, &module, NULL);~%")
                (format stream "    free(spirv_data);~%")
                (format stream "    if (result != ZE_RESULT_SUCCESS) {~%")
                (format stream "        printf(\"ERROR: zeModuleCreate failed: %%d\\n\", result);~%")
                (format stream "        return 1;~%")
                (format stream "    }~%")
                (format stream "    printf(\"Module loaded successfully\\n\");~%~%"))

          (format stream "    // TODO: Create kernel~%")
          (format stream "    // TODO: Set kernel arguments~%")
          (format stream "    // TODO: Create command list and queue~%")
          (format stream "    // TODO: Launch kernel~%")
          (format stream "    // TODO: Cleanup~%~%")

          (format stream "    printf(\"Success!\\n\");~%")
          (format stream "    return 0;~%")
          (format stream "}~%"))

        (format t "  Done: ~a~%" (namestring output-path))))))
