(in-package :crisp.hoist.l0)

(defun main ()
  "Entry point for crisp-hoist-l0.exe"
  (handler-case
      (let ((args (uiop:command-line-arguments)))
        (format t "Crisp Hoist L0 - Level Zero C++ Launcher Generator~%")
        (format t "Version: 0.3.0~%~%")

        (unless args
          (format t "Usage: crisp-hoist-l0 <path-to-metacrisp-file>~%")
          (uiop:quit 1))

        (let ((metacrisp-path (first args)))
          (unless (probe-file metacrisp-path)
            (format t "Error: File not found: ~a~%" metacrisp-path)
            (uiop:quit 1))

          (format t "Processing: ~a~%" metacrisp-path)
          (generate-l0-launcher metacrisp-path)
          (format t "Done!~%")
          (uiop:quit 0)))
    (error (e)
      (format t "Error: ~a~%" e)
      (uiop:quit 1))))

(defun generate-l0-launcher (metacrisp-path)
  "Generate Level Zero C++ launcher code from metacrisp file."
  (let* ((data (parse-metacrisp-file metacrisp-path))
         (kernels (metacrisp-kernels data))
         (aliases (metacrisp-aliases data))
         (base-name (pathname-name metacrisp-path)))

    (format t "Processing ~a~%" metacrisp-path)
    (format t "  Kernels: ~a~%" (length kernels))

    ;; Generate one .cpp file per kernel
    (dolist (kernel kernels)
      (let* ((kernel-name (getf kernel :name))
             (declared-sig (getf kernel :declared-signature))
             (output-targets (getf kernel :output-targets))
             (spv-path (when output-targets
                             (second (first output-targets)))) ;; Get first .spv path
             (output-name (format nil "~a_~a_hoist_L0.cpp" base-name kernel-name))
             (output-path (make-pathname :name (pathname-name output-name)
                                         :type "cpp"
                                         :defaults metacrisp-path)))

        (format t "  Generating: ~a~%" output-name)

        ;; Generate Level Zero C++ launcher
        (with-open-file (stream output-path :direction :output :if-exists :supersede)
          (generate-cpp-preamble stream metacrisp-path kernel-name output-name)
          (generate-cpp-includes stream)
          (generate-cpp-typedefs stream aliases)
          (generate-cpp-helpers stream)
          (generate-cpp-main stream kernel-name spv-path declared-sig))

        (format t "  Done: ~a~%" (namestring output-path))))))

(defun generate-cpp-preamble (stream metacrisp-path kernel-name output-name)
  "Generate C++ file preamble comment"
  (format stream "/*~%")
  (format stream " * Generated by crisp-hoist-l0~%")
  (format stream " * Source: ~a~%" (namestring metacrisp-path))
  (format stream " * Kernel: ~a~%" kernel-name)
  (format stream " *~%")
  (format stream " * Compilation:~%")
  (format stream " *   g++ -o launcher ~a -I<path-to-level-zero>/include~%" output-name)
  (format stream " *~%")
  (format stream " * Level Zero SDK: https://github.com/oneapi-src/level-zero/releases~%")
  (format stream " */~%~%"))

(defun generate-cpp-includes (stream)
  "Generate C++ includes"
  (format stream "#include <ze_api.h>~%")
  (format stream "#include <iostream>~%")
  (format stream "#include <fstream>~%")
  (format stream "#include <vector>~%")
  (format stream "#include <cstring>~%~%"))

(defun generate-cpp-typedefs (stream aliases)
  "Generate C++ typedef declarations from type aliases"
  (when aliases
        (format stream "// Type aliases~%")
        (dolist (alias-def aliases)
          (when (and (listp alias-def) (>= (length alias-def) 3))
                (let ((alias-name (string-downcase (symbol-name (second alias-def))))
                      (target-type (string-downcase (symbol-name (third alias-def)))))
                  (format stream "typedef ~a ~a;~%" target-type alias-name))))
        (format stream "~%")))

(defun generate-cpp-helpers (stream)
  "Generate C++ helper functions"
  (format stream "// Helper: Read SPIR-V binary from file~%")
  (format stream "std::vector<uint8_t> read_spirv_file(const char* filename) {~%")
  (format stream "    std::ifstream file(filename, std::ios::binary | std::ios::ate);~%")
  (format stream "    if (!file) {~%")
  (format stream "        throw std::runtime_error(\"Failed to open SPIR-V file\");~%")
  (format stream "    }~%")
  (format stream "    size_t size = file.tellg();~%")
  (format stream "    std::vector<uint8_t> buffer(size);~%")
  (format stream "    file.seekg(0);~%")
  (format stream "    file.read(reinterpret_cast<char*>(buffer.data()), size);~%")
  (format stream "    return buffer;~%")
  (format stream "}~%~%"))

(defun generate-cpp-main (stream kernel-name spv-path declared-sig)
  "Generate C++ main function"
  (format stream "int main() {~%")
  (format stream "    ze_result_t result;~%")
  (format stream "    std::cout << \"Level Zero Launcher for kernel: ~a\" << std::endl;~%~%" kernel-name)

  ;; L0 Initialization
  (generate-l0-init stream)

  ;; Module loading
  (when spv-path
        (generate-module-loading stream spv-path))

  ;; Kernel creation and launch
  (generate-kernel-launch stream kernel-name declared-sig)

  (format stream "    std::cout << \"Success!\" << std::endl;~%")
  (format stream "    return 0;~%")
  (format stream "}~%"))

(defun generate-l0-init (stream)
  "Generate Level Zero initialization code"
  (format stream "    // Initialize Level Zero~%")
  (format stream "    result = zeInit(ZE_INIT_FLAG_GPU_ONLY);~%")
  (format stream "    if (result != ZE_RESULT_SUCCESS) {~%")
  (format stream "        std::cerr << \"ERROR: zeInit failed: \" << result << std::endl;~%")
  (format stream "        return 1;~%")
  (format stream "    }~%~%")

  (format stream "    // Discover drivers~%")
  (format stream "    uint32_t driverCount = 0;~%")
  (format stream "    result = zeDriverGet(&driverCount, nullptr);~%")
  (format stream "    if (result != ZE_RESULT_SUCCESS || driverCount == 0) {~%")
  (format stream "        std::cerr << \"ERROR: No Level Zero drivers found\" << std::endl;~%")
  (format stream "        return 1;~%")
  (format stream "    }~%~%")

  (format stream "    ze_driver_handle_t driver;~%")
  (format stream "    driverCount = 1;~%")
  (format stream "    zeDriverGet(&driverCount, &driver);~%~%")

  (format stream "    // Discover devices~%")
  (format stream "    uint32_t deviceCount = 0;~%")
  (format stream "    result = zeDeviceGet(driver, &deviceCount, nullptr);~%")
  (format stream "    if (result != ZE_RESULT_SUCCESS || deviceCount == 0) {~%")
  (format stream "        std::cerr << \"ERROR: No Level Zero devices found\" << std::endl;~%")
  (format stream "        return 1;~%")
  (format stream "    }~%~%")

  (format stream "    ze_device_handle_t device;~%")
  (format stream "    deviceCount = 1;~%")
  (format stream "    zeDeviceGet(driver, &deviceCount, &device);~%")
  (format stream "    std::cout << \"Found Level Zero device\" << std::endl;~%~%")

  (format stream "    // Create context~%")
  (format stream "    ze_context_desc_t contextDesc = { ZE_STRUCTURE_TYPE_CONTEXT_DESC };~%")
  (format stream "    ze_context_handle_t context;~%")
  (format stream "    result = zeContextCreate(driver, &contextDesc, &context);~%")
  (format stream "    if (result != ZE_RESULT_SUCCESS) {~%")
  (format stream "        std::cerr << \"ERROR: zeContextCreate failed: \" << result << std::endl;~%")
  (format stream "        return 1;~%")
  (format stream "    }~%~%"))

(defun generate-module-loading (stream spv-path)
  "Generate SPIR-V module loading code"
  (format stream "    // Load SPIR-V module~%")
  (format stream "    const char* spv_path = \"~a\";~%" (namestring spv-path))
  (format stream "    std::vector<uint8_t> spirv_data;~%")
  (format stream "    try {~%")
  (format stream "        spirv_data = read_spirv_file(spv_path);~%")
  (format stream "    } catch (const std::exception& e) {~%")
  (format stream "        std::cerr << \"ERROR: \" << e.what() << std::endl;~%")
  (format stream "        return 1;~%")
  (format stream "    }~%~%")

  (format stream "    ze_module_desc_t moduleDesc = {~%")
  (format stream "        ZE_STRUCTURE_TYPE_MODULE_DESC,~%")
  (format stream "        nullptr,~%")
  (format stream "        ZE_MODULE_FORMAT_IL_SPIRV,~%")
  (format stream "        spirv_data.size(),~%")
  (format stream "        spirv_data.data(),~%")
  (format stream "        nullptr,~%")
  (format stream "        nullptr~%")
  (format stream "    };~%~%")

  (format stream "    ze_module_handle_t module;~%")
  (format stream "    result = zeModuleCreate(context, device, &moduleDesc, &module, nullptr);~%")
  (format stream "    if (result != ZE_RESULT_SUCCESS) {~%")
  (format stream "        std::cerr << \"ERROR: zeModuleCreate failed: \" << result << std::endl;~%")
  (format stream "        return 1;~%")
  (format stream "    }~%")
  (format stream "    std::cout << \"Module loaded successfully\" << std::endl;~%~%"))

(defun generate-kernel-launch (stream kernel-name declared-sig)
  "Generate kernel creation and launch code"
  (format stream "    // Create kernel~%")
  (format stream "    ze_kernel_desc_t kernelDesc = { ZE_STRUCTURE_TYPE_KERNEL_DESC };~%")
  (format stream "    kernelDesc.pKernelName = \"~a\";~%" kernel-name)
  (format stream "    ze_kernel_handle_t kernel;~%")
  (format stream "    result = zeKernelCreate(module, &kernelDesc, &kernel);~%")
  (format stream "    if (result != ZE_RESULT_SUCCESS) {~%")
  (format stream "        std::cerr << \"ERROR: zeKernelCreate failed: \" << result << std::endl;~%")
  (format stream "        return 1;~%")
  (format stream "    }~%~%")

  ;; Set kernel arguments if any
  (when declared-sig
        (generate-kernel-arguments-with-usm stream declared-sig "context" "device"))

  ;; Create command list and queue
  (format stream "    // Create command list~%")
  (format stream "    ze_command_list_desc_t cmdListDesc = { ZE_STRUCTURE_TYPE_COMMAND_LIST_DESC };~%")
  (format stream "    ze_command_list_handle_t cmdList;~%")
  (format stream "    result = zeCommandListCreate(context, device, &cmdListDesc, &cmdList);~%")
  (format stream "    if (result != ZE_RESULT_SUCCESS) {~%")
  (format stream "        std::cerr << \"ERROR: zeCommandListCreate failed: \" << result << std::endl;~%")
  (format stream "        return 1;~%")
  (format stream "    }~%~%")

  (format stream "    // Create command queue~%")
  (format stream "    ze_command_queue_desc_t cmdQueueDesc = { ZE_STRUCTURE_TYPE_COMMAND_QUEUE_DESC };~%")
  (format stream "    ze_command_queue_handle_t cmdQueue;~%")
  (format stream "    result = zeCommandQueueCreate(context, device, &cmdQueueDesc, &cmdQueue);~%")
  (format stream "    if (result != ZE_RESULT_SUCCESS) {~%")
  (format stream "        std::cerr << \"ERROR: zeCommandQueueCreate failed: \" << result << std::endl;~%")
  (format stream "        return 1;~%")
  (format stream "    }~%~%")

  ;; Launch kernel
  (format stream "    // Launch kernel~%")
  (format stream "    ze_group_count_t groupCount = { 1, 1, 1 };~%")
  (format stream "    result = zeCommandListAppendLaunchKernel(cmdList, kernel, &groupCount, nullptr, 0, nullptr);~%")
  (format stream "    if (result != ZE_RESULT_SUCCESS) {~%")
  (format stream "        std::cerr << \"ERROR: zeCommandListAppendLaunchKernel failed: \" << result << std::endl;~%")
  (format stream "        return 1;~%")
  (format stream "    }~%~%")

  (format stream "    // Close and execute command list~%")
  (format stream "    zeCommandListClose(cmdList);~%")
  (format stream "    zeCommandQueueExecuteCommandLists(cmdQueue, 1, &cmdList, nullptr);~%")
  (format stream "    zeCommandQueueSynchronize(cmdQueue, UINT64_MAX);~%~%")

  (format stream "    std::cout << \"Kernel executed successfully\" << std::endl;~%~%"))

(defun generate-kernel-arguments (stream declared-sig)
  "Generate kernel argument setup code"
  (format stream "    // Set kernel arguments~%")
  (let ((arg-index 0))
    (dolist (param declared-sig)
      (let ((param-name (getf param :name))
            (param-type (getf param :type)))
        ;; For now, just handle scalar types
        (when (symbolp param-type) ; Simple scalar type
              (format stream "    ~a ~a_arg = ~d;  // TODO: Set actual value~%"
                (string-downcase (symbol-name param-type))
                param-name
                (+ arg-index 42)) ; Placeholder value
              (format stream "    zeKernelSetArgumentValue(kernel, ~d, sizeof(~a), &~a_arg);~%~%"
                arg-index
                (string-downcase (symbol-name param-type))
                param-name)
              (incf arg-index))))
    (when (> arg-index 0)
          (format stream "~%"))))
;; Helper function to check if a type is a cell
(defun cell-type-p (param-type)
  "Check if a parameter type is a cell type"
  (and (listp param-type)
       (symbolp (first param-type))
       (string-equal (symbol-name (first param-type)) "CELL")))

;; Helper function to extract base type from cell
(defun cell-base-type (param-type)
  "Extract the base type from a cell type like (cell int ...)"
  (when (cell-type-p param-type)
        (second param-type)))

;; Updated generate-kernel-arguments to handle both scalars and cells
(defun generate-kernel-arguments-with-usm (stream declared-sig context-var device-var)
  "Generate kernel argument setup code with USM allocation for cells"
  (format stream "    // Set up kernel arguments~%")
  (let ((arg-index 0)
        (allocations '())) ; Track allocations for cleanup

    (dolist (param declared-sig)
      (let ((param-name (getf param :name))
            (param-type (getf param :type))
            (param-dir (getf param :direction)))

        (cond
         ;; Handle cell parameters (pointers/buffers)
         ((cell-type-p param-type)
           (let* ((base-type (cell-base-type param-type))
                  (base-type-str (string-downcase (symbol-name base-type)))
                  (size-var (format nil "~a_size" param-name))
                  (ptr-var (format nil "~a_ptr" param-name)))

             ;; Allocate USM shared memory
             (format stream "~%    // Allocate USM memory for ~a~%" param-name)
             (format stream "    size_t ~a = 16;  // TODO: Actual size~%" size-var)
             (format stream "    ~a* ~a = nullptr;~%" base-type-str ptr-var)
             (format stream "    result = zeMemAllocShared(~a, ~a, ~%"
               context-var device-var)
             (format stream "        nullptr, ~a * sizeof(~a), 1, &~a);~%"
               size-var base-type-str ptr-var)
             (format stream "    if (result != ZE_RESULT_SUCCESS) {~%")
             (format stream "        std::cerr << \"ERROR: zeMemAllocShared failed for ~a\" << std::endl;~%"
               param-name)
             (format stream "        return 1;~%")
             (format stream "    }~%")

             ;; Initialize input buffers
             (when (eq param-dir :in)
                   (format stream "    // Initialize input data~%")
                   (format stream "    for (size_t i = 0; i < ~a; i++) {~%" size-var)
                   (format stream "        ~a[i] = static_cast<~a>(i);  // TODO: Actual data~%"
                     ptr-var base-type-str)
                   (format stream "    }~%"))

             ;; Set kernel argument
             (format stream "    zeKernelSetArgumentValue(kernel, ~d, sizeof(void*), &~a);~%~%"
               arg-index ptr-var)

             ;; Track allocation for cleanup
             (push (list :name param-name :ptr ptr-var) allocations)
             (incf arg-index)))

         ;; Handle scalar parameters  
         ((symbolp param-type)
           (format stream "    ~a ~a_arg = ~d;  // TODO: Set actual value~%"
             (string-downcase (symbol-name param-type))
             param-name
             (+ arg-index 42))
           (format stream "    zeKernelSetArgumentValue(kernel, ~d, sizeof(~a), &~a_arg);~%~%"
             arg-index
             (string-downcase (symbol-name param-type))
             param-name)
           (incf arg-index)))))

    ;; Return allocations for later cleanup
    (nreverse allocations)))
