;;;; overlays/hoist-cuda/crisp-hoist-cuda-overlay.lisp
;;;;
;;;; Runtime patches for CUDA hoist improvements.
;;;; Applied via late binding - last definition wins.

(in-package :crisp.hoist.cuda)


;;; =====================================================================
;;; Endeavor 143 — tile-grid dispatch for CUDA (port of the L0 fix)
;;;
;;; `emit-launch`'s :strided branch emitted `gridY = 1, gridZ = 1` and referenced :tile-shape
;;; ZERO times — structurally the same bug fixed on the L0 side.  Under an N-dimensional
;;; tile-stride loop the axes left at 1 are serialized inside each block; results stay correct,
;;; so the only symptom is lost throughput.
;;;
;;; Differences from L0, both worth knowing:
;;;
;;;   * CUDA has NO units bug.  cuOccupancyMaxActiveBlocksPerMultiprocessor x numSMs returns
;;;     BLOCKS and is per-kernel register-aware — a real occupancy query, which Level Zero
;;;     lacks.  The :strided sizing is left exactly as it was.
;;;   * The bug is MASKED for every benchmarked chapter: the --mma-bench out-tile override
;;;     above it emits (M/TM x N/TN), so chap1.5 / chap2 / chap3_wgmma never reached the broken
;;;     branch and their published numbers are sound.  This fix is for kernels that declare
;;;     :strategy :strided + :tile-shape and hoist normally.
;;;
;;; AXIS MAPPING: axis 0 <- tensor dimension 0 (rows).  Three independent agreements: the BMG
;;; measurement (1.31x on a non-square 512x2048), the hand-written L0 bench harness
;;; ({M/TM, N/TN, 1}), and this file's own out-tile override, whose comment reads
;;; "gridX = row-tiles, gridY = col-tiles".
;;;
;;; DEVICE LIMITS ARE REACHABLE HERE, unlike on Intel.  H100 reports
;;; maxGridDim X/Y/Z = 2147483647 / 65535 / 65535 (measured 2026-07-26).  A 32-tile cover
;;; exceeds gridDimY at N ~ 2.1M, so the clamp is live rather than theoretical:
;;;   :strided -> clamp and note (the tile-stride loop covers the remainder — safe)
;;;   :exact   -> hard error (no loop, so a clamp would silently skip tiles)
;;;
;;; emit-launch below is EXTRACTED VERBATIM from src/hoist-cuda/main.lisp with one cond branch
;;; spliced in — generated by put_temp_files_here/make_cuda_overlay.py so nothing is retyped.

;; src/hoist-cuda/main.lisp
(defun %cuda-tensor-extent-cpp-var (sym k)
  "C++ per-dimension extent variable for a tensor parameter: <name>_ext<k>.
   The flat <name>_length that %tensor-length-cpp-var yields carries no shape and so cannot
   size a rank-N grid — dividing it by a tile width is what the old :exact tensor branch did."
  (format nil "~a_ext~d" (substitute #\_ #\- (string-downcase (symbol-name sym))) k))

;; src/hoist-cuda/main.lisp
(defun %cuda-emit-tile-grid (stream derive-from derive-from-is-tensor tile-shape can-stride)
  "Emit gridX/gridY/gridZ covering the output tile grid: ceil(extent[k] / tile[k]) per axis,
   axis k drawn from dimension k of the :derive-from source, then guard against the device's
   maxGridDim.  CAN-STRIDE (i.e. :strided) decides clamp-vs-error; see the header comment."
  (let* ((axis-vars '("gridX" "gridY" "gridZ"))
         (axis-attrs '("CU_DEVICE_ATTRIBUTE_MAX_GRID_DIM_X"
                       "CU_DEVICE_ATTRIBUTE_MAX_GRID_DIM_Y"
                       "CU_DEVICE_ATTRIBUTE_MAX_GRID_DIM_Z"))
         (rank (min (length tile-shape) 3))
         (declared '()))
    (format stream "    // :tile-shape ~a — one block per output tile; axis k <- dimension k.~%"
            tile-shape)
    (dotimes (k 3)
      (let* ((var (nth k axis-vars))
             (tk  (when (< k rank) (or (nth k tile-shape) 1)))
             (src (when (< k rank)
                    (if derive-from-is-tensor
                        (when (first derive-from)
                          (%cuda-tensor-extent-cpp-var (first derive-from) k))
                        (when (nth k derive-from)
                          (%dispatch-sym-to-cpp-var (nth k derive-from)))))))
        (if (and src tk (> tk 0))
            (progn
              (format stream "    unsigned int ~a = (unsigned int)(((unsigned long long)~a + ~d) / ~d);~%"
                      var src (1- tk) tk)
              (format stream "    if (~a < 1) ~a = 1;~%" var var)
              (push (list var (nth k axis-attrs)) declared))
            ;; Axes past the tile-shape rank are a literal 1 — still declared, because
            ;; cuLaunchKernel below references all three unconditionally.
            (format stream "    unsigned int ~a = 1;~%" var))))
    (when declared
      (format stream "    // Device grid limits.  H100: X=2^31-1 but Y/Z=65535, so a tile grid~%")
      (format stream "    // (which scales with the PROBLEM, not the hardware) can genuinely exceed them.~%")
      (dolist (axis (nreverse declared))
        (destructuring-bind (var attr) axis
          (format stream "    { int _lim = 0; cuDeviceGetAttribute(&_lim, ~a, device);~%" attr)
          (format stream "      if (_lim > 0 && ~a > (unsigned int)_lim) {~%" var)
          (if can-stride
              (progn
                (format stream "        std::cerr << \"NOTE: ~a \" << ~a << \" exceeds device limit \" << _lim~%" var var)
                (format stream "                  << \"; clamping — the tile-stride loop covers the rest.\" << std::endl;~%")
                (format stream "        ~a = (unsigned int)_lim;~%" var))
              (progn
                (format stream "        std::cerr << \"ERROR: ~a \" << ~a << \" exceeds device limit \" << _lim~%" var var)
                (format stream "                  << \". :strategy :exact has no stride loop, so clamping would skip\"~%")
                (format stream "                  << \" tiles.  Use :strategy :strided for a problem this large.\" << std::endl;~%")
                (format stream "        return;~%")))
          (format stream "      } }~%"))))))

;; src/hoist-cuda/main.lisp
(defun emit-launch (stream dispatch-info shared-bytes &optional compute-units kernel-name out-tile)
  "Emit cuLaunchKernel call with grid/block dims from dispatch-info.
   OUT-TILE (TM TN), when set (--mma-bench), OVERRIDES the grid with a (M/TM x N/TN) 2-D grid.
   Supports:
     :strategy :strided        — max occupancy (cuOccupancyMaxActiveBlocksPerMultiprocessor)
     :strategy :one-thread-per — grid sized to derive-from source
     :strategy :exact          — grid sized via derive-from / local-size (or tile-shape if present)
     :set-to integer/list      — fixed grid
   And :derive-from can be a single tensor symbol (uses <name>_length) or a list
   of scalar parameter names (uses <name>_arg).
   COMPUTE-UNITS, when non-NIL, is the active hardware profile's :compute-units;
   the :strided strategy then uses that fixed SM count instead of querying the
   device (CU_DEVICE_ATTRIBUTE_MULTIPROCESSOR_COUNT), so a shrunken profile takes
   effect host-side.
   Endeavor 140 (dynamic-SMEM opt-in): a kernel needing >48KB SMEM (n128-pipe, n256, wgmma
   big-tile, ...) must cuFuncSetAttribute MAX_DYNAMIC_SHARED_SIZE_BYTES or the launch silently
   fails (CUDA_ERROR_INVALID_VALUE)."
  ;; sm_90 reserves ~1KB of the 48KB default, so even exactly-48KB (49152) dynamic SMEM needs the
  ;; opt-in; n64-pipe (32768) launches fine without it, so 32768 is the safe cutoff.  Emitted
  ;; before the grid/launch code so the attribute is set prior to cuLaunchKernel.
  (when (and shared-bytes (> shared-bytes 32768))
    (format stream "    CUDA_CHECK(cuFuncSetAttribute(kernel, CU_FUNC_ATTRIBUTE_MAX_DYNAMIC_SHARED_SIZE_BYTES, ~d));~%"
            shared-bytes))
  (let* ((global-decl     (when dispatch-info (getf dispatch-info :global-size)))
         (local-decl      (when dispatch-info (getf dispatch-info :local-size)))
         (num-groups-decl (when dispatch-info (getf dispatch-info :num-groups)))

         (ls-rest    (when local-decl (cdr local-decl)))
         (ls-set-to  (when ls-rest (getf ls-rest :set-to)))
         (block-x    (cond ((integerp ls-set-to) ls-set-to)
                           ((and (consp ls-set-to) (first ls-set-to)) (first ls-set-to))
                           (t 1)))
         (block-y    (cond ((and (consp ls-set-to) (second ls-set-to)) (second ls-set-to))
                           (t 1)))

         (dispatch-decl (or global-decl num-groups-decl))
         (disp-rest  (when dispatch-decl (cdr dispatch-decl)))
         (set-to     (when disp-rest (getf disp-rest :set-to)))
         (raw-derive-from (when disp-rest (getf disp-rest :derive-from)))
         (derive-from-is-tensor (%derive-from-is-tensor-p raw-derive-from))
         (derive-from (%normalize-derive-from raw-derive-from))
         (strategy    (when disp-rest (getf disp-rest :strategy)))
         (strat-name  (when strategy (symbol-name strategy)))
         (is-strided  (and strat-name (string-equal strat-name "STRIDED")))
         (is-exact    (and strat-name (string-equal strat-name "EXACT")))
         (is-one-thread-per (or (and strat-name (string-equal strat-name "ONE-THREAD-PER"))
                                ;; default when :derive-from is present without explicit strategy
                                (and (null strat-name) derive-from)))
         (tile-shape  (when disp-rest (getf disp-rest :tile-shape)))
         ;; :occupancy <ratio> — manual derating for :strided (default 1.0)
         (occupancy   (when disp-rest (getf disp-rest :occupancy))))

    (format stream "    // Launch kernel~%")

    (cond
      ;; --- Endeavor 137 --mma-bench grid override: (M/TM x N/TN) 2-D output-tile grid ---
      ;; gridX = row-tiles (grid-y = workgroup-id 0), gridY = col-tiles (grid-x = workgroup-id 1),
      ;; matching matrix-multiply-tile-stride's mapping (and the 136 bench_harness.cu).
      ((and out-tile *mma-test-dims*)
       (destructuring-bind (m n k) *mma-test-dims*
         (declare (ignore k))
         (destructuring-bind (tm tn) out-tile
           (format stream "    unsigned int gridX = ~d, gridY = ~d, gridZ = 1;  // (M/~d, N/~d) output-tile grid~%"
                   (ceiling m tm) (ceiling n tn) tm tn))))

      ;; --- :tile-shape — rank-N tile grid (Endeavor 143; ported from the L0 hoist) ---
      ;; Must precede :strided.  A 1-D grid under an N-D tile-stride loop does not merely
      ;; under-dispatch, it SERIALIZES the missing axes (measured 7.6x on Intel BMG).  The
      ;; --mma-bench out-tile override above still wins when it is set.
      ((and tile-shape derive-from (or is-strided is-exact))
       (%cuda-emit-tile-grid stream derive-from derive-from-is-tensor tile-shape is-strided))

      ;; --- :strategy :strided — max occupancy (optionally derated by :occupancy) ---
      (is-strided
       (let ((block-size (* block-x (max 1 block-y)))
             (ratio (cond ((null occupancy) 1.0)
                          ((numberp occupancy) (float occupancy))
                          (t 1.0))))
         (format stream "    // Strategy: :strided — max occupancy via cuOccupancyMaxActiveBlocksPerMultiprocessor~%")
         (when derive-from-is-tensor
           (format stream "    // derive-from tensor '~a' (length=~a) used for check-thread-bounds; grid uses occupancy~%"
                   (first derive-from) (%tensor-length-cpp-var (first derive-from))))
         (format stream "    int _blocksPerSM;~%")
         (format stream "    CUDA_CHECK(cuOccupancyMaxActiveBlocksPerMultiprocessor(&_blocksPerSM, kernel, ~d, ~a));~%"
                 block-size shared-bytes)
         (if compute-units
             (progn
               (format stream "    // Hardware profile active: :compute-units overrides the device SM query~%")
               (format stream "    int _numSMs = ~d;~%" compute-units))
             (progn
               (format stream "    int _numSMs;~%")
               (format stream "    CUDA_CHECK(cuDeviceGetAttribute(&_numSMs, CU_DEVICE_ATTRIBUTE_MULTIPROCESSOR_COUNT, device));~%")))
         (if (= ratio 1.0)
             (format stream "    unsigned int gridX = (unsigned int)(_blocksPerSM * _numSMs);~%")
             (progn
               (format stream "    // :occupancy ~a — user-requested derate from max~%" occupancy)
               (format stream "    unsigned int gridX = (unsigned int)((_blocksPerSM * _numSMs) * ~f);~%" ratio)
               (format stream "    if (gridX < 1) gridX = 1;~%")))
         (format stream "    unsigned int gridY = 1, gridZ = 1;~%")))

      ;; --- :set-to integer — fixed grid ---
      ((and (not is-exact) (integerp set-to))
       (let ((grid-x (if (> block-x 1)
                         (format nil "(~a + ~a) / ~a" set-to (1- block-x) block-x)
                         (format nil "~a" set-to))))
         (format stream "    unsigned int gridX = ~a, gridY = 1, gridZ = 1;~%" grid-x)))

      ;; --- :strategy :exact with :derive-from ---
      (is-exact
       (if derive-from-is-tensor
           ;; Tensor-derived exact: gridX = ceil(<tensor>_length / tx)
           (let ((tx (if tile-shape (or (first tile-shape) 1) block-x))
                 (tensor-var (%tensor-length-cpp-var (first derive-from))))
             (format stream "    unsigned int gridX = ((unsigned int)~a + ~d) / ~d;~%"
                     tensor-var (1- tx) tx)
             (format stream "    unsigned int gridY = 1, gridZ = 1;~%"))
           ;; Scalar list exact
           (let ((d0 (first derive-from))
                 (d1 (second derive-from))
                 (tx (if tile-shape (or (first tile-shape) 1) block-x))
                 (ty (if tile-shape (or (second tile-shape) 1) (if (> block-y 1) block-y 1))))
             (when d0
               (format stream "    unsigned int gridX = ((unsigned int)~a + ~a) / ~a;~%"
                       (%dispatch-sym-to-cpp-var d0) (1- tx) tx))
             (when d1
               (format stream "    unsigned int gridY = ((unsigned int)~a + ~a) / ~a;~%"
                       (%dispatch-sym-to-cpp-var d1) (1- ty) ty))
             (unless d0 (format stream "    unsigned int gridX = 1;~%"))
             (unless d1 (format stream "    unsigned int gridY = 1;~%"))
             (format stream "    unsigned int gridZ = 1;~%"))))

      ;; --- :strategy :one-thread-per (or unstated default) + :derive-from <tensor> ---
      ((and is-one-thread-per derive-from-is-tensor)
       (let ((tensor-var (%tensor-length-cpp-var (first derive-from))))
         (format stream "    // Strategy: :one-thread-per from tensor ~a~%" (first derive-from))
         (if (> block-x 1)
             (format stream "    unsigned int gridX = ((unsigned int)~a + ~d) / ~d;~%"
                     tensor-var (1- block-x) block-x)
             (format stream "    unsigned int gridX = (unsigned int)~a;~%" tensor-var))
         (format stream "    unsigned int gridY = 1, gridZ = 1;~%")))

      ;; --- :set-to list OR :derive-from (scalar list) ---
      ((or (consp set-to) derive-from)
       (let* ((dims (cond ((consp set-to) set-to)
                          (derive-from derive-from)
                          (t nil)))
              (d0 (first dims))
              (d1 (second dims)))
         (flet ((dim-gc (dim local-val)
                  (cond
                    ((null dim) "1")
                    ((integerp dim)
                     (if (> local-val 1)
                         (format nil "(~a + ~a) / ~a" dim (1- local-val) local-val)
                         (format nil "~a" dim)))
                    ((symbolp dim)
                     (let ((v (%dispatch-sym-to-cpp-var dim)))
                       (if (> local-val 1)
                           (format nil "((unsigned int)~a + ~a) / ~a" v (1- local-val) local-val)
                           (format nil "(unsigned int)~a" v))))
                    (t "1"))))
           (format stream "    unsigned int gridX = ~a, gridY = ~a, gridZ = 1;~%"
                   (dim-gc d0 block-x)
                   (dim-gc d1 (if (> block-y 1) block-y 1))))))

      ;; --- Default fallback ---
      (t
       (format stream "    unsigned int gridX = 1, gridY = 1, gridZ = 1;~%")))

    ;; Repeatable launch — one call for the correctness readback that follows, and (for
    ;; --mma-bench) the timed relaunch loop below.
    ;; Plain launch (no CUDA_CHECK — its `return` would make this void lambda non-void AND
    ;; swallow errors from the timed loop); a launch error surfaces at the cuCtxSynchronize below.
    (format stream "    auto _crisp_launch = [&]() {~%")
    (format stream "      CUresult _lr = cuLaunchKernel(kernel,~%")
    (format stream "          gridX, gridY, gridZ,~%")
    (format stream "          ~a, ~a, 1,~%" block-x block-y)
    (format stream "          ~a, 0,~%" shared-bytes)
    (format stream "          kernelParams, nullptr);~%")
    (format stream "      if (_lr != CUDA_SUCCESS) { const char* _es; cuGetErrorString(_lr, &_es);~%")
    (format stream "        std::cerr << \"launch error: \" << _es << std::endl; }~%")
    (format stream "    };~%")
    (format stream "    _crisp_launch();~%~%")
    ;; Endeavor 137: --mma-bench — warmup + timed relaunch loop -> GFLOPS.  Each launch fully
    ;; recomputes C (per-tile reset), so the final C is still correct for the readback check.
    (when (and *mma-bench-p* *mma-test-dims*)
      (destructuring-bind (m n k) *mma-test-dims*
        (format stream "    {  // --mma-bench: timed relaunch loop~%")
        (format stream "      const int WARMUP = 20, ITERS = 100;~%")
        (format stream "      for (int _w = 0; _w < WARMUP; _w++) _crisp_launch();~%")
        (format stream "      CUDA_CHECK(cuCtxSynchronize());~%")
        (format stream "      CUevent _s, _e; cuEventCreate(&_s, 0); cuEventCreate(&_e, 0);~%")
        (format stream "      cuEventRecord(_s, 0);~%")
        (format stream "      for (int _i = 0; _i < ITERS; _i++) _crisp_launch();~%")
        (format stream "      cuEventRecord(_e, 0); cuEventSynchronize(_e);~%")
        (format stream "      float _ms = 0.0f; cuEventElapsedTime(&_ms, _s, _e);~%")
        (format stream "      double _gflops = (2.0 * ~d.0 * ~d.0 * ~d.0 * ITERS) / (_ms * 1.0e6);~%" m n k)
        (format stream "      std::cout << \"BENCH ~a ~dx~dx~d: \" << _gflops << \" GFLOPS (\" << (_ms/ITERS) << \" ms/iter)\" << std::endl;~%"
                (or kernel-name "kernel") m n k)
        (format stream "      cuEventDestroy(_s); cuEventDestroy(_e);~%")
        (format stream "    }~%~%")))))

;;; -----------------------------------------------------------------------
;;; Readback and output printing
;;; -----------------------------------------------------------------------
