;; tests/spec/052-differentiate-sub-functions/sub-func-ad.unit.lisp
;;
;; Unit tests for the sub-function autodiff helpers (feature 052).
;; Covers: %backward-skip-fn-p, %generate-backward-function-walk,
;;         and %generate-backward-function-ast.

(in-package :crisp.tests)

(define-test sub-func-ad-test
  "Tests for 052 sub-function autodiff helpers.")

;;; Helper: intern a symbol in :crisp-language so all adjoint symbols
;;; generated by local-adj end up in the same package.
(defun %052-sym (name)
  (intern name (find-package :crisp-language)))

;;; Helper: check whether a nested form contains a specific symbol anywhere.
(defun %052-tree-contains-p (tree sym)
  (cond
    ((eq tree sym) t)
    ((consp tree) (or (%052-tree-contains-p (cl:first tree) sym)
                      (%052-tree-contains-p (cl:rest  tree) sym)))
    (t nil)))

;;; =========================================================
;;; %backward-skip-fn-p
;;; =========================================================

(define-test (sub-func-ad-test skip-fn-system-generated)
  "Functions whose names contain % are system-generated and should be skipped."
  (true  (crisp.compiler::%backward-skip-fn-p (%052-sym "%CONSTRUCT-STRUCT")))
  (true  (crisp.compiler::%backward-skip-fn-p (%052-sym "MAKE-FAKE-CELL%DISPATCH")))
  (true  (crisp.compiler::%backward-skip-fn-p (%052-sym "%ANF-HELPER"))))

(define-test (sub-func-ad-test skip-fn-as-casts)
  "AS (bitcast) and AS-* (derived-type coercions) are always skipped."
  (true  (crisp.compiler::%backward-skip-fn-p (%052-sym "AS")))
  (true  (crisp.compiler::%backward-skip-fn-p (%052-sym "AS-INT")))
  (true  (crisp.compiler::%backward-skip-fn-p (%052-sym "AS-COORDINATE")))
  (true  (crisp.compiler::%backward-skip-fn-p (%052-sym "AS-METERS"))))

(define-test (sub-func-ad-test skip-fn-integer-conversions)
  "TO-<int-type> conversions are skipped (integer output, no float adjoint)."
  (true  (crisp.compiler::%backward-skip-fn-p (%052-sym "TO-INT")))
  (true  (crisp.compiler::%backward-skip-fn-p (%052-sym "TO-UINT")))
  (true  (crisp.compiler::%backward-skip-fn-p (%052-sym "TO-ULONG")))
  (true  (crisp.compiler::%backward-skip-fn-p (%052-sym "TO-SHORT")))
  (true  (crisp.compiler::%backward-skip-fn-p (%052-sym "TO-CHAR"))))

(define-test (sub-func-ad-test skip-fn-user-functions-not-skipped)
  "Ordinary user functions are not skipped — they go through B1 or B3."
  (false (crisp.compiler::%backward-skip-fn-p (%052-sym "MY-FN")))
  (false (crisp.compiler::%backward-skip-fn-p (%052-sym "SOME-OPERATION")))
  (false (crisp.compiler::%backward-skip-fn-p (%052-sym "TO-CELSIUS")))  ; TO- but not int suffix
  (false (crisp.compiler::%backward-skip-fn-p (%052-sym "DISTANCE"))))

;;; =========================================================
;;; %generate-backward-function-walk — addition rule
;;; =========================================================

(define-test (sub-func-ad-test gfbw-addition-rule)
  "For (V (+ A B)), backward walk accumulates A_ADJ += V_ADJ and B_ADJ += V_ADJ."
  (cl:let* ((pkg  (find-package :crisp-language))
             (a    (intern "A052ADD" pkg))
             (b    (intern "B052ADD" pkg))
             (v    (intern "V052ADD" pkg))
             (tg   (intern "T_GRAD052ADD" pkg))
             ;; flat-anf: one binding then the return symbol
             (flat-anf (list (list v (list '+ a b)) v))
             (result (crisp.compiler::%generate-backward-function-walk
                       flat-anf (list a b) (list tg) (list v))))
    ;; Result is (let (...) ...)
    (is eq 'let (cl:first result))
    ;; Bindings contain an adjoint for V seeded by T-GRAD
    (cl:let* ((bindings (cl:second result))
               (v-adj   (intern "V052ADD_ADJ" pkg))
               (a-adj   (intern "A052ADD_ADJ" pkg))
               (b-adj   (intern "B052ADD_ADJ" pkg))
               (v-bind  (find v-adj bindings :key #'cl:first))
               (a-bind  (find a-adj bindings :key #'cl:first))
               (b-bind  (find b-adj bindings :key #'cl:first)))
      (true  v-bind)
      (is eq tg (cl:second v-bind))   ; V_ADJ seeded with T-GRAD
      (true  a-bind)
      (is = 0.0 (cl:second a-bind))   ; A_ADJ starts at 0.0
      (true  b-bind)
      (is = 0.0 (cl:second b-bind)))  ; B_ADJ starts at 0.0
    ;; Body contains set! accumulation for A and B
    (cl:let* ((body     (cddr result))
               (a-adj   (intern "A052ADD_ADJ" pkg))
               (b-adj   (intern "B052ADD_ADJ" pkg)))
      (true (%052-tree-contains-p body a-adj))
      (true (%052-tree-contains-p body b-adj)))
    ;; Last form in body is (return A_ADJ B_ADJ)
    (cl:let* ((body     (cddr result))
               (ret     (cl:car (cl:last body)))
               (a-adj   (intern "A052ADD_ADJ" pkg))
               (b-adj   (intern "B052ADD_ADJ" pkg)))
      (is eq 'return (cl:first ret))
      (true (%052-tree-contains-p ret a-adj))
      (true (%052-tree-contains-p ret b-adj)))))

;;; =========================================================
;;; %generate-backward-function-walk — multiplication rule
;;; =========================================================

(define-test (sub-func-ad-test gfbw-multiplication-rule)
  "For (V (* A B)), backward walk: A_ADJ += B*V_ADJ, B_ADJ += A*V_ADJ."
  (cl:let* ((pkg  (find-package :crisp-language))
             (a    (intern "A052MUL" pkg))
             (b    (intern "B052MUL" pkg))
             (v    (intern "V052MUL" pkg))
             (tg   (intern "T_GRAD052MUL" pkg))
             (flat-anf (list (list v (list '* a b)) v))
             (result (crisp.compiler::%generate-backward-function-walk
                       flat-anf (list a b) (list tg) (list v))))
    (is eq 'let (cl:first result))
    ;; Body must contain A_ADJ and B_ADJ accumulators, each involving the other var
    (cl:let* ((body  (cddr result))
               (a-adj (intern "A052MUL_ADJ" pkg))
               (b-adj (intern "B052MUL_ADJ" pkg)))
      ;; Both A_ADJ and B_ADJ should appear in the body
      (true (%052-tree-contains-p body a-adj))
      (true (%052-tree-contains-p body b-adj))
      ;; A_ADJ accumulation should involve B (the co-factor)
      (cl:let ((a-set-form (find a-adj (cl:butlast body)
                                 :test (lambda (sym form) (%052-tree-contains-p form sym)))))
        (true a-set-form)
        (true (%052-tree-contains-p a-set-form b)))
      ;; B_ADJ accumulation should involve A (the co-factor)
      (cl:let ((b-set-form (find b-adj (cl:butlast body)
                                 :test (lambda (sym form) (%052-tree-contains-p form sym)))))
        (true b-set-form)
        (true (%052-tree-contains-p b-set-form a))))))

;;; =========================================================
;;; %generate-backward-function-walk — B2.5 struct accessor (name ends in ~)
;;; =========================================================

(define-test (sub-func-ad-test gfbw-struct-accessor-identity)
  "For (V (FIELD~ A)) where FIELD~ ends in ~, adjoint propagates as identity: A_ADJ += V_ADJ."
  (cl:let* ((pkg     (find-package :crisp-language))
             (a       (intern "A052ACC" pkg))
             (v       (intern "V052ACC" pkg))
             (tg      (intern "T_GRAD052ACC" pkg))
             (field~  (intern "FIELD~" pkg))
             (flat-anf (list (list v (list field~ a)) v))
             (result  (crisp.compiler::%generate-backward-function-walk
                        flat-anf (list a) (list tg) (list v))))
    (is eq 'let (cl:first result))
    ;; A_ADJ should appear and be seeded from V_ADJ (identity through accessor)
    (cl:let* ((body  (cddr result))
               (a-adj (intern "A052ACC_ADJ" pkg))
               (v-adj (intern "V052ACC_ADJ" pkg)))
      (true (%052-tree-contains-p body a-adj))
      ;; The accumulation for A_ADJ should reference V_ADJ (identity rule)
      (cl:let ((set-form (find a-adj (cl:butlast body)
                               :test (lambda (sym form) (%052-tree-contains-p form sym)))))
        (true set-form)
        (true (%052-tree-contains-p set-form v-adj))))))

;;; =========================================================
;;; %generate-backward-function-walk — B1 known sub-function call
;;; =========================================================

(define-test (sub-func-ad-test gfbw-known-subfn-call)
  "For (V (MULTIPLY A B)) where MULTIPLY is in *differentiable-functions*,
backward walk emits a call to MULTIPLY_GRAD and accumulates deltas."
  (initialize-compiler)
  (cl:let* ((pkg     (find-package :crisp-language))
             (a       (intern "A052SFUN" pkg))
             (b       (intern "B052SFUN" pkg))
             (v       (intern "V052SFUN" pkg))
             (tg      (intern "T_GRAD052SFUN" pkg))
             (mult    (intern "MULTIPLY052" pkg))
             (mult-g  (intern "MULTIPLY052_GRAD" pkg))
             (flat-anf (list (list v (list mult a b)) v)))
    ;; Register MULTIPLY in the differentiable-functions table
    (setf (gethash mult crisp.compiler::*differentiable-functions*)
          (list :bkwd-name mult-g :n-float-params 2 :n-return 1))
    (cl:let ((result (crisp.compiler::%generate-backward-function-walk
                       flat-anf (list a b) (list tg) (list v))))
      ;; Result is a let form
      (is eq 'let (cl:first result))
      ;; Body must contain a reference to MULTIPLY_GRAD
      (cl:let ((body (cddr result)))
        (true (%052-tree-contains-p body mult-g)))
      ;; Body must accumulate adjoints for A and B
      (cl:let* ((body  (cddr result))
                 (a-adj (intern "A052SFUN_ADJ" pkg))
                 (b-adj (intern "B052SFUN_ADJ" pkg)))
        (true (%052-tree-contains-p body a-adj))
        (true (%052-tree-contains-p body b-adj))))))

;;; =========================================================
;;; %generate-backward-function-ast — end-to-end for a simple function
;;; =========================================================

(define-test (sub-func-ad-test gbfa-simple-add-function)
  "For (def-function add052 (a b) (declare #'(float float => float)) (+ a b)),
%generate-backward-function-ast produces a valid ADD052_GRAD def-function form."
  (initialize-compiler)
  (cl:let* ((pkg   (find-package :crisp-language))
             (name  (intern "ADD052" pkg))
             (a     (intern "A" pkg))
             (b     (intern "B" pkg))
             (params (list a b))
             (declarations
              (list `(function (float float => float))))
             (body-forms (list (list '+ a b)))
             (result (crisp.compiler::%generate-backward-function-ast
                       name params declarations body-forms)))
    ;; Returns a def-function form
    (true result)
    (is eq 'def-function (cl:first result))
    ;; Name is ADD052_GRAD
    (cl:let ((bkwd-name (intern "ADD052_GRAD" pkg)))
      (is eq bkwd-name (cl:second result)))
    ;; Function is registered in *differentiable-functions*
    (cl:let ((entry (gethash name crisp.compiler::*differentiable-functions*)))
      (true entry)
      (is = 2 (getf entry :n-float-params))
      (is = 1 (getf entry :n-return)))))

(define-test (sub-func-ad-test gbfa-skips-non-float-params)
  "A function with no float params produces NIL — nothing to differentiate."
  (initialize-compiler)
  (cl:let* ((pkg   (find-package :crisp-language))
             (name  (intern "INT-ADD052" pkg))
             (a     (intern "A" pkg))
             (b     (intern "B" pkg))
             (params (list a b))
             (declarations (list `(function (int int => int))))
             (body-forms (list (list '+ a b)))
             (result (crisp.compiler::%generate-backward-function-ast
                       name params declarations body-forms)))
    (false result)))

(define-test (sub-func-ad-test gbfa-graceful-on-non-differentiable-body)
  "A function whose body calls an unknown user function (not differentiable, not skippable)
returns NIL gracefully rather than signalling an error.
The function is unregistered from *differentiable-functions* after the failure."
  (initialize-compiler)
  (cl:let* ((pkg       (find-package :crisp-language))
             (name      (intern "WRAPPER052" pkg))
             (f         (intern "F" pkg))
             (params    (list f))
             (declarations (list `(function (float => float))))
             ;; Body: calls SOME-OPAQUE-FN052 which is not registered as differentiable
             ;; and not in the skip list -- will hit B3 in GFBW, triggering handler-case.
             (body-forms (list (list (intern "SOME-OPAQUE-FN052" pkg) f)))
             (result (crisp.compiler::%generate-backward-function-ast
                       name params declarations body-forms)))
    ;; Must return NIL -- no error thrown, gracefully skipped
    (false result)
    ;; WRAPPER052 must NOT be left registered as differentiable
    (false (gethash name crisp.compiler::*differentiable-functions*))))
